### ISSUE TITLE
Expected 1 EncryptedAssertion; found 0.

### ISSUE THREAD

**Issue by rahil471** [Clever/saml2#118] opened 2017-11-02 12:39 UTC
I'm trying to implement this keeping the `allow_unencrypted_assertions` option to false. 
I generated a certificate and private key pair and provided it to saml2. 
After redirecting to asset I encounter this Error. 

`Expected 1 EncryptedAssertion; found 0.` 

An I missing something?

**Comment by kabirbaidhya** [comment] 2017-12-13 09:32
Same here. I'm getting this issue too. Can anyone explain what the issue is about or what needs configured to get it fixed?

**Comment by astone123** [comment] 2018-06-20 16:42
Are you sure that your IdP is sending an encrypted response? When I was configuring my SP, I was getting this error until I set `allow_unencrypted_assertions: true` in my SP options.

It turned out that the response I was getting from my IdP was just base64-encoded XML, so no need for a private key to decrypt it. If your IdP isn't sending an encrypted response, I think this option needs to be set to `true` for it to work correctly.

**Comment by MrCorncob** [comment] 2018-11-20 08:21
May be outdated but follow the documents at https://www.npmjs.com/package/saml2-js#ServiceProvider, you can set the option `allow_unencrypted_assertion: true` to allow assertion without encryption.
(It's ** allow_unencrypted_assertion** instead of **allow_unencrypted_assertions**)

**Comment by mcab** [comment] 2021-02-03 19:21
Given the documentation provided and the relative quiet on the issue, I'm going to close this out.

Thanks MrCorncob for responding. Reopen this issue or file a new issue if you're still encountering an issue.

**Closed by mcab** 2021-02-03 19:21 UTC
